### ISSUE TITLE
支持在现有模型之上训练吗？

### ISSUE THREAD

**Issue by oohurbert** [breezedeus/cnocr#10]
原来的那个项目有load_epoch可以加载现有模型，现在可以在下载的0200之上训练吗？
我试了一下，有报错。
python scripts/cnocr_train.py --dataset cn_ocr --load_epoch 0020
proc 0 started
proc 1 started
proc 2 started
proc 3 started
proc 0 started
proc 1 started
2019-04-25 23:42:32,320 Loaded model ./models/model_0020.params
Process Process-2:
Traceback (most recent call last):
  File "/////lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "////python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "////cnocr/cnocr/data_utils/multiproc_data.py", line 89, in _proc_loop
    data = fn()
  File "////cnocr/cnocr/data_utils/data_iter.py", line 212, in _gen_sample
    labels[idx - 1] = int(img_lst[idx])
IndexError: index 10 is out of bounds for axis 0 with size 10
Process Process-4:

**Comment by breezedeus** [comment]
@oohurbert 之前的版本不能这么做，v1.0.0已经支持了~
