### ISSUE TITLE
请问参数cand_alphabet如何使用，为何我的报错了

### ISSUE THREAD

**Issue by arckalsun** [breezedeus/cnocr#108]
我想只识别数字，于是我看了代码，如下
```python
class CnOcr(object):
    MODEL_FILE_PREFIX = 'cnocr-v{}'.format(MODEL_VERSION)

    def __init__(
        self,
        model_name='densenet-lite-fc',
        model_epoch=None,
        cand_alphabet=None,
        root=data_dir(),
        context='cpu',
        name=None,
    ):
        """

        :param model_name: 模型名称
        :param model_epoch: 模型迭代次数
        :param cand_alphabet: 待识别字符所在的候选集合。默认为 `None`，表示不限定识别字符范围
        :param root: 模型文件所在的根目录。
            Linux/Mac下默认值为 `~/.cnocr`，表示模型文件所处文件夹类似 `~/.cnocr/1.1.0/conv-lite-fc-0027`。
            Windows下默认值为 ``。
        :param context: 'cpu', or 'gpu'。表明预测时是使用CPU还是GPU。默认为CPU。
        :param name: 正在初始化的这个实例名称。如果需要同时初始化多个实例，需要为不同的实例指定不同的名称。
        """
```
我是这样用的
`digital_ocr = CnOcr(cand_alphabet=['0','1','2','3','4','5','6','7','8','9'])`
但是在运行时报错了，报错信息如下
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Work/ProcessTaken/tests/test_locater.py", line 10, in <module>
    from core import locater
  File "D:\Work\ProcessTaken\core\locater.py", line 13, in <module>
    from core.img2str import ocr
  File "D:\Work\ProcessTaken\core\img2str.py", line 28, in <module>
    digital_ocr = CnOcr(cand_alphabet=['0','1','2','3','4','5','6','7','8','9',':'])
  File "D:\Work\ProcessTaken\venv\lib\site-packages\cnocr\cn_ocr.py", line 175, in __init__
    self._mod = self._get_module(context)
  File "D:\Work\ProcessTaken\venv\lib\site-packages\cnocr\cn_ocr.py", line 211, in _get_module
    context=context,
  File "D:\Work\ProcessTaken\venv\lib\site-packages\cnocr\cn_ocr.py", line 122, in load_module
    mod.set_params(arg_params, aux_params, allow_missing=False)
  File "D:\Work\ProcessTaken\venv\lib\site-packages\mxnet\module\module.py", line 350, in set_params
    allow_extra=allow_extra)
  File "D:\Work\ProcessTaken\venv\lib\site-packages\mxnet\module\module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "D:\Work\ProcessTaken\venv\lib\site-packages\mxnet\module\module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: crnn1_seq-fc_bias is not presented

```
这个该如何处理

**Comment by breezedeus** [comment]
你是不是初始化了多个实例？初始化多个需要传入不同的 `name`。
