### ISSUE TITLE
使用pip在Windows 10上安装失败

### ISSUE THREAD

**Issue by jj11hh** [breezedeus/cnocr#115]
```
Collecting cnocr
  Using cached https://files.pythonhosted.org/packages/cf/1c/9c0ef41ee6c57a52c9e80c1508f90917033e6821a30ff9d82809e7b23677/cnocr-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ihen\appdata\local\temp\pip-install-gygobi\cnocr\setup.py", line 10, in <module> 
        long_description = (here / "README.md").read_text(encoding="utf-8")
    AttributeError: 'WindowsPath' object has no attribute 'read_text'
```
我尝试在Windows上安装它，我的Python版本是3.8，请问这是为什么呢

**Comment by jj11hh** [comment]
找到原因了，我用了Python 2的PIP，换用Python 3后解决
