### ISSUE TITLE
安装后mxnet无法正确import，提示缺少DLL文件。

### ISSUE THREAD

**Issue by ipdear** [breezedeus/cnocr#128]
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\base.py", line 214, in <module>
    _LIB = _load_lib()
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\base.py", line 204, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\libinfo.py", line 74, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the MXNet library.
List of candidates:
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\libmxnet.dll
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../lib/libmxnet.dll
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../build/libmxnet.dll
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../build\libmxnet.dll
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../build\Release\libmxnet.dll
C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mxnet\../../windows\Release\libmxnet.dll

**Comment by breezedeus** [comment]
mxnet没装好，Windows下要装vs，可以搜一下具体怎么装

**Comment by zhonghai9967** [comment]
同问。我装了VS开发工具，还是不行。
