### ISSUE TITLE
训练时发生错误，没有什么头绪，能帮看看吗

### ISSUE THREAD

**Issue by halloweens1** [breezedeus/cnocr#131]
D:\cnocr\cnocr>python scripts/cnocr_train.py --gpu 0 --emb_model_type densenet-lite --seq_model_type gru --optimizer adam --epoch 20 --lr 1e-4 --train_file datasets/self_dataset_003-lst/sample-data_train --test_file datasets/self_dataset_003-lst/sample-data_test
[INFO 2020-12-07 00:12:54,547 train_cnocr:129] save models to dir: C:\Users\Lusons Joe\AppData\Roaming\cnocr\1.2.0\densenet-lite-gru
[INFO 2020-12-07 00:12:54,566 __init__:1203] Using 1 threads for decoding...
[INFO 2020-12-07 00:12:54,566 __init__:1204] Set enviroment variable MXNET_CPU_WORKER_NTHREADS to a larger number to use more threads.
[INFO 2020-12-07 00:12:54,567 __init__:1208] GrayImageIter: loading recordio datasets/self_dataset_003-lst/sample-data_train.rec...
[INFO 2020-12-07 00:12:54,573 __init__:1203] Using 1 threads for decoding...
[INFO 2020-12-07 00:12:54,574 __init__:1204] Set enviroment variable MXNET_CPU_WORKER_NTHREADS to a larger number to use more threads.
[INFO 2020-12-07 00:12:54,575 __init__:1208] GrayImageIter: loading recordio datasets/self_dataset_003-lst/sample-data_test.rec...
[INFO 2020-12-07 00:12:54,581 fit:22] hp: {'_num_epoch': 20, '_loss_type': 'ctc', 'optimizer': 'adam', '_learning_rate': 0.0001, 'wd': 0.0, 'clip_gradient': None, '_batch_size': 128, '_num_classes': 6426, '_img_width': 280, '_img_height': 32, 'seq_model_type': 'gru', '_num_hidden': 128, '_num_lstm_layer': 1, 'seq_len_cmpr_ratio': 4, '_seq_length': 70, '_num_label': 20, '_drop_out': 0.5}
Traceback (most recent call last):
  File "scripts/cnocr_train.py", line 214, in <module>
    train_cnocr(args)
  File "scripts/cnocr_train.py", line 146, in train_cnocr
    fit(
  File "D:\cnocr\cnocr\cnocr\fit\fit.py", line 48, in fit
    module.fit(
  File "D:\Python38\lib\site-packages\mxnet\module\base_module.py", line 520, in fit
    next_data_batch = next(data_iter)
  File "D:\Python38\lib\site-packages\mxnet\io\io.py", line 230, in __next__
    return self.next()
  File "D:\cnocr\cnocr\cnocr\data_utils\data_iter.py", line 331, in next
    data_batch = super().next()
  File "D:\Python38\lib\site-packages\mxnet\image\image.py", line 1389, in next
    i = self._batchify(batch_data, batch_label)
  File "D:\Python38\lib\site-packages\mxnet\image\image.py", line 1360, in _batchify
    batch_label[i] = label
  File "D:\Python38\lib\site-packages\mxnet\ndarray\ndarray.py", line 535, in __setitem__
    self._set_nd_basic_indexing(key, value)
  File "D:\Python38\lib\site-packages\mxnet\ndarray\ndarray.py", line 991, in _set_nd_basic_indexing
    value_nd = self._prepare_value_nd(value, bcast_shape=bcast_shape, squeeze_axes=new_axes)
  File "D:\Python38\lib\site-packages\mxnet\ndarray\ndarray.py", line 767, in _prepare_value_nd
    value_nd = value_nd.broadcast_to(bcast_shape)
  File "D:\Python38\lib\site-packages\mxnet\ndarray\ndarray.py", line 2290, in broadcast_to
    raise ValueError(err_str)
ValueError: operands could not be broadcast together with remapped shapes[original->remapped]: (106,) and requested shape (20,)

**Comment by breezedeus** [comment]
每张图片里的字数量最多20。看看是不是有图片有更多的字
