### ISSUE TITLE
初始化出问题你们都没有出现吗？

### ISSUE THREAD

**Issue by jiacheng1gujiaxin** [breezedeus/cnocr#139]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from monitor import monitor
  File "/home/ai/Desktop/project/RemoteMonitor/monitor.py", line 44, in <module>
    time_rec = time_recognition()
  File "/home/ai/Desktop/project/RemoteMonitor/ocr/cnocr_api.py", line 10, in __init__
    self.ocr_rec = CnOcr(model_name=model_name, context=device)
  File "/home/ai/anaconda3/envs/torch/lib/python3.8/site-packages/cnocr/cn_ocr.py", line 178, in __init__
    self._mod = self._get_module(context)
  File "/home/ai/anaconda3/envs/torch/lib/python3.8/site-packages/cnocr/cn_ocr.py", line 207, in _get_module
    mod = load_module(
  File "/home/ai/anaconda3/envs/torch/lib/python3.8/site-packages/cnocr/cn_ocr.py", line 125, in load_module
    mod.set_params(arg_params, aux_params, allow_missing=False)
  File "/home/ai/anaconda3/envs/torch/lib/python3.8/site-packages/mxnet/module/module.py", line 348, in set_params
    self.init_params(initializer=None, arg_params=arg_params, aux_params=aux_params,
  File "/home/ai/anaconda3/envs/torch/lib/python3.8/site-packages/mxnet/module/module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "/home/ai/anaconda3/envs/torch/lib/python3.8/site-packages/mxnet/module/module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: densenet1_batchnorm0_beta is not presented

**Comment by junity233** [comment]
+1
