### ISSUE TITLE
树莓派zero w pip安装后无法使用

### ISSUE THREAD

**Issue by Playfullycat** [breezedeus/cnocr#140]
>>> from cnocr import CnOcr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/cnocr/__init__.py", line 1, in <module>
    from .cn_ocr import CnOcr
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/cnocr/cn_ocr.py", line 21, in <module>
    import mxnet as mx
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/pi/.virtualenvs/cv/lib/python3.7/site-packages/mxnet/libmxnet.so: wrong ELF class: ELFCLASS64

**Comment by Fisherworks** [comment]
这个问题应该pi用户都会遇到，主要是mxnet的python包不是为Raspbian 32bit系统编译所致，跟本项目应该没有太大关系
我在尝试自己编译raspbian的mxnet库，但花了大半天编译的是2.0.0版本，本项目要求1.6.0版本，我没有编成功

**Comment by Fisherworks** [comment]
直接在mxnet repo下载之前release打包的1.6.0代码，树莓派上编译 mxnet python库（armv7l 32bit）
安装后就能跑cnocr了，只不过要打破依赖，把numpy 1.19.5卸载掉，装上1.20.1，pi上跑cnocr完全没问题

**Comment by Fisherworks** [comment]
刚意识到你想用zero w
那恐怕要非常在意你的内存消耗，我测试的是1000x100分辨率的图上，大概有三行共100多字，在pi3 4核ARM 上要吃到400M内存，12s左右计算时间
按zero w的机能，你不仅要考虑内存的问题，核数和频率恐怕也得琢磨一下咯
