### ISSUE TITLE
成功安装后，执行报错

### ISSUE THREAD

**Issue by ChenZhaobin** [breezedeus/cnocr#141]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from cnocr import CnOcr
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\cnocr\__init__.py", line 1, in <module>
    from .cn_ocr import CnOcr
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\cnocr\cn_ocr.py", line 21, in <module>
    import mxnet as mx
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\__init__.py", line 31, in <module>
    from . import contrib
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\__init__.py", line 31, in <module>
    from . import onnx
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\__init__.py", line 19, in <module>
    from .onnx2mx.import_model import import_model, get_model_metadata
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\onnx2mx\__init__.py", line 20, in <module>
    from . import import_model
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\onnx2mx\import_model.py", line 22, in <module>
    from .import_onnx import GraphProto
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\onnx2mx\import_onnx.py", line 26, in <module>
    from ._import_helper import _convert_map as convert_map
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\onnx2mx\_import_helper.py", line 21, in <module>
    from ._op_translations import identity, random_uniform, random_normal, sample_multinomial
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\onnx2mx\_op_translations.py", line 22, in <module>
    from . import _translation_utils as translation_utils
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\onnx2mx\_translation_utils.py", line 23, in <module>
    from .... import  module
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\module\__init__.py", line 22, in <module>
    from .base_module import BaseModule
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\module\base_module.py", line 31, in <module>
    from ..model import BatchEndParam
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\mxnet\model.py", line 46, in <module>
    from sklearn.base import BaseEstimator
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Users\10706\AppData\Roaming\Python\Python37\site-packages\sklearn\_distributor_init.py", line 23, in <module>
    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by ChenZhaobin** [comment]
重新装了一下python，并删除原有的packages就好了。
看了一下效果，空格的识别不是太理想，很多单词会粘连到一起
