### ISSUE TITLE
图片大小是否有最小限制

### ISSUE THREAD

**Issue by diorw** [breezedeus/cnocr#154]
请问图片有大小限制嘛，我是一个狭长的一个图片。报错

`Traceback (most recent call last):
  File "/Users/wda/PycharmProjects/table-detect/image.py", line 288, in <module>
    res = ocr.ocr('img/1.png')
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/cnocr/cn_ocr.py", line 191, in ocr
    line_chars_list = self.ocr_for_single_lines(line_img_list)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/cnocr/cn_ocr.py", line 259, in ocr_for_single_lines
    out = self._predict(img_list)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/cnocr/cn_ocr.py", line 286, in _predict
    out = self._model(
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/cnocr/models/ocr_model.py", line 185, in forward
    features = self.encoder(x)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/cnocr/models/densenet.py", line 72, in forward
    features = self.features(x)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/wda/miniforge3/envs/tf_2/lib/python3.9/site-packages/torch/nn/modules/pooling.py", line 615, in forward
    return F.avg_pool2d(input, self.kernel_size, self.stride,
RuntimeError: Given input size: (64x8x1). Calculated output size: (64x4x0). Output size is too small`

**Comment by diorw** [comment]
我有两张相同大小 31*208 的图片 24-bit color；包含几个中文，一张可以识别，一张报如上错误

**Comment by diorw** [comment]
![image](https://user-images.githubusercontent.com/23721111/131208849-12ae879a-8260-4092-891c-eb2c9e14266a.png)这张图片报错

**Comment by breezedeus** [comment]
嗯，对，有最小限制。太小的图片可能会报错。
