### ISSUE TITLE
2.0以后版本使用pyinstaller打包有问题

### ISSUE THREAD

**Issue by cgstian** [breezedeus/cnocr#156]
aa.py内容
from cnocr import CnOcr

btocr = CnOcr()
只这两行代码，打包出来277M，

并且无法运行，
报错
```
[172864] WARNING: file already exists but should not: C:\Users\**\AppData\Local\Temp\_MEI*******\torch\_C.cp37-win_amd64.pyd
Traceback (most recent call last):
  File "aa.py", line 3, in <module>
  File "cnocr\cn_ocr.py", line 105, in __init__
  File "cnocr\utils.py", line 243, in read_charset
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\**\\AppData\Local\\Temp\\_MEI*******\\cnocr\\label_cn.txt'
[180220] Failed to execute script 'aa' due to unhandled exception!
```

**Comment by breezedeus** [comment]
没试过打包。label_cn.txt 这个文件找不到，可以手动下载到对应的地方？

**Comment by yexiiiemm** [comment]
请问最后的解决办法是什么呢

**Comment by bobocha214** [comment]
> 请问最后的解决办法是什么呢
可以看看我的博客，我写的程序就找不到cnocr的包，得自己添加，希望能解决你的问题

https://blog.csdn.net/want_stars/article/details/131571365?spm=1001.2014.3001.5502

**Comment by helloWordppp** [comment]
初始化CnOcr时，指定label_cn.txt的地址

CnOcr(rec_vocab_fp=label_cn)

rec_vocab_fp (Optional[Union[str, Path]]): 识别字符集合的文件路径，即 `label_cn.txt` 文件路径。取值为 `None` 表示使用系统设定的词表。
                若训练的自有模型更改了字符集，看通过此参数传入新的字符集文件路径。
