### ISSUE TITLE
http server did not work

### ISSUE THREAD

**Issue by l1t1** [breezedeus/CnOCR#213]
I started the server
```
D:\>cnocr serve -p 8501
[INFO 2022-10-19 16:31:23,375 _get_model:178] use model: C:\Users\LD\AppData\Roaming\cnocr\2.2\densenet_lite_136-fc\cnocr-v2.2-densenet_lite_136-fc-ep
och=039-complete_match_epoch=0.8597-model.onnx
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an error set
[WARNING 2022-10-19 16:31:23,739 _showwarnmsg:109] d:\python38\lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupport
ed Windows version (7). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(

[INFO 2022-10-19 16:31:23,813 _assert_and_prepare_model_files:135] use model: C:\Users\LD\AppData\Roaming\cnstd\1.2\ppocr\ch_PP-OCRv3_det_infer.onnx
[32mINFO[0m:     Started server process [[36m14776[0m]
[INFO 2022-10-19 16:31:23,936 serve:84] Started server process [14776]
[32mINFO[0m:     Waiting for application startup.
[INFO 2022-10-19 16:31:23,937 startup:45] Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[INFO 2022-10-19 16:31:23,938 startup:59] Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8501[0m (Press CTRL+C to quit)
[INFO 2022-10-19 16:31:23,939 _log_started_message:217] Uvicorn running on http://0.0.0.0:8501 (Press CTRL+C to quit)
```
then open another console and run curl command, return empty.
```
D:\>curl -F image=@dddz.png http://0.0.0.0:8501/ocr
curl: (52) Empty reply from server

D:\>curl -F image=@dddz1.png http://0.0.0.0:8501/ocr
curl: (26) Failed to open/read local data from file/application
```

I  tried following code from https://cnocr.readthedocs.io/zh/latest/, also failed

```
import requests

image_fp = 'dddz.png'
r = requests.post('http://0.0.0.0:8501/ocr', files={'image': (image_fp, open(image_fp, 'rb'), 'image/png')},)
ocr_out = r.json()['results']
print(ocr_out)
```

output
```
D:\>python
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>>
>>> image_fp = 'dddz.png'
>>> r = requests.post('http://0.0.0.0:8501/ocr', files={'image': (image_fp, open(image_fp, 'rb'), 'image/png')},)
Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "D:\Python38\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "D:\Python38\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [WinError 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\Python38\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Python38\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\Python38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Python38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Python38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Python38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "D:\Python38\lib\http\client.py", line 950, in send
    self.connect()
  File "D:\Python38\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "D:\Python38\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000000035E9700>: Failed to establish a new connection: [WinErr
or 10049] 在其上下文中，该请求的地址无效。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\Python38\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=8501): Max retries exceeded with url: /ocr (Caused by NewConnectionError('<u
rllib3.connection.HTTPConnection object at 0x00000000035E9700>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无效
。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python38\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python38\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8501): Max retries exceeded with url: /ocr (Caused by NewConnectionError(
'<urllib3.connection.HTTPConnection object at 0x00000000035E9700>: Failed to establish a new connection: [WinError 10049] 在其上下文中，该请求的地址无
效。'))
>>>

```

**Comment by breezedeus** [comment]
Your server didn't start as expected. Solve the problem first.

```
D:\>cnocr serve -p 8501
[INFO 2022-10-19 16:31:23,375 _get_model:178] use model: C:\Users\LD\AppData\Roaming\cnocr\2.2\densenet_lite_136-fc\cnocr-v2.2-densenet_lite_136-fc-ep
och=039-complete_match_epoch=0.8597-model.onnx
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import
```

**Comment by l1t1** [comment]
so i need to install numpy 0xe? which version is 0xe?

**Comment by breezedeus** [comment]
try to reinstall numpy. I think your numpy is ruined.

**Comment by breezedeus** [comment]
my numpy：

```bash
✗ pip show numpy
Name: numpy
Version: 1.23.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD
Location: /Users/king/Documents/WhatIHaveDone/Test/cnocr/venv/lib/python3.8/site-packages
```

**Comment by l1t1** [comment]
I upgrade the numpy and restart server,  the problem still exists.
```
D:\>curl -F image=@dddz.png http://0.0.0.0:8501/ocr
curl: (52) Empty reply from server

D:\>pip show numpy
Name: numpy
Version: 1.23.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: d:\python38\lib\site-packages
Requires:
Required-by: xarray, wordcloud, vaex-core, torchvision, torchmetrics, tensorflow, tensorboard, taichi, scipy, pytorch-lightning, pythreejs, pyerfa, py
arrow, pandas, opt-einsum, opencv-python, onnxruntime, onnx, numba, monetdbe, matplotlib, Keras-Preprocessing, ipyvolume, ipydatawidgets, h5py, gensim
, duckdb, cupy-cuda101, cnstd, cnocr, bqplot, astropy
```

server
```
D:\>cnocr serve -p 8501
[INFO 2022-10-21 15:55:13,266 _get_model:178] use model: C:\Users\LD\AppData\Roaming\cnocr\2.2\densenet_lite_136-fc\cnocr-v2.2-densenet_lite_136-fc-ep
och=039-complete_match_epoch=0.8597-model.onnx
[WARNING 2022-10-21 15:55:13,628 _showwarnmsg:109] d:\python38\lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupport
ed Windows version (7). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(

[INFO 2022-10-21 15:55:13,710 _assert_and_prepare_model_files:135] use model: C:\Users\LD\AppData\Roaming\cnstd\1.2\ppocr\ch_PP-OCRv3_det_infer.onnx
[32mINFO[0m:     Started server process [[36m23752[0m]
[INFO 2022-10-21 15:55:13,827 serve:84] Started server process [23752]
[32mINFO[0m:     Waiting for application startup.
[INFO 2022-10-21 15:55:13,828 startup:45] Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[INFO 2022-10-21 15:55:13,830 startup:59] Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:8501[0m (Press CTRL+C to quit)
[INFO 2022-10-21 15:55:13,833 _log_started_message:217] Uvicorn running on http://0.0.0.0:8501 (Press CTRL+C to quit)
```

**Comment by breezedeus** [comment]
i don't see any exception in your messages.

**Comment by l1t1** [comment]
curl -F image=@dddz.png http://0.0.0.0:8501   returns empty response. 
and the code

import requests

image_fp = 'dddz.png'
r = requests.post('http://0.0.0.0:8501/ocr', files={'image': (image_fp, open(image_fp, 'rb'), 'image/png')},)
ocr_out = r.json()['results']
print(ocr_out)
 returns same error message of oldversion numpy.
