### ISSUE TITLE
Http服务启动报错

### ISSUE THREAD

**Issue by Jinnrry** [breezedeus/CnOCR#225]
背景：[官方提供的Docker镜像](https://hub.docker.com/r/breezedeus/cnocr/tags)占用空间过大，且官方镜像无lastest tag，导致使用不便。因此尝试自己编译一个小尺寸的Docker镜像

Dockerfile:

```
FROM python:3.8

RUN apt-get update && apt-get install -y python3-opencv libglib2.0-0 libsm6 libxext6 libxrender-dev

RUN pip install -U pip && pip install torch==1.11.0 \
    && pip install -U cnocr[serve]==2.2.2 --extra-index-url https://pypi.org/simple

CMD ["cnocr", "serve", "-H", "0.0.0.0", "-p", "8501"]
EXPOSE 8501
```

错误信息：

```
/usr/local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/usr/local/bin/cnocr", line 5, in <module>
    from cnocr.cli import cli
  File "/usr/local/lib/python3.8/site-packages/cnocr/__init__.py", line 30, in <module>
    from .cn_ocr import CnOcr
  File "/usr/local/lib/python3.8/site-packages/cnocr/cn_ocr.py", line 37, in <module>
    from .recognizer import Recognizer
  File "/usr/local/lib/python3.8/site-packages/cnocr/recognizer.py", line 31, in <module>
    from .models.ocr_model import OcrModel
  File "/usr/local/lib/python3.8/site-packages/cnocr/models/ocr_model.py", line 34, in <module>
    from .mobilenet import gen_mobilenet_v3
  File "/usr/local/lib/python3.8/site-packages/cnocr/models/mobilenet.py", line 25, in <module>
    from torchvision.models.mobilenetv2 import ConvBNActivation
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (/usr/local/lib/python3.8/site-packages/torchvision/models/mobilenetv2.py)
```

**Comment by breezedeus** [comment]
看看 torchvision 的版本，不要用 >=0.14

**Comment by Jinnrry** [comment]
确实是torchvision版本问题，降级后问题解决。最终Dockerfile
```
FROM python:3.8

RUN apt-get update && apt-get install -y python3-opencv libglib2.0-0 libsm6 libxext6 libxrender-dev

RUN  pip install torchvision==0.13  torch==1.11.0  cnocr[serve]==2.2.2

CMD ["cnocr", "serve", "-H", "0.0.0.0", "-p", "8501"]

EXPOSE 8501
```
