### ISSUE TITLE
windows系统用cnocr出现问题 

### ISSUE THREAD

**Issue by zhang0557kui** [breezedeus/cnocr#23]
[17:12:04] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v1.3.1. Attempting to upgrade...
[17:12:04] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1523, in simple_bind
    ctypes.byref(exe_handle)))
  File "C:\Program Files\Anaconda3\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:12:04] c:\jenkins\workspace\mxnet-tag\mxnet\src\executor\../common/exec_utils.h:392: InferShape pass cannot decide shapes for the following arguments (0s means unknown dimensions). Please consider providing them as inputs:
l0_init_h: [], l2_init_h: [], l1_init_h: [], l3_init_h: [], 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/文件/OCR项目/新OCR项目/OCR/testocr.py", line 4, in <module>
    ocr = CnOcr()
  File "D:\文件\OCR项目\新OCR项目\OCR\cnocr2\cnocr\cn_ocr.py", line 107, in __init__
    self._mod = self._get_module(self._hp)
  File "D:\文件\OCR项目\新OCR项目\OCR\cnocr2\cnocr\cn_ocr.py", line 134, in _get_module
    mod = load_module(prefix, self._model_epoch, data_names, data_shapes, network=network)
  File "D:\文件\OCR项目\新OCR项目\OCR\cnocr2\cnocr\cn_ocr.py", line 90, in load_module
    mod.bind(for_training=False, data_shapes=data_shapes)
  File "C:\Program Files\Anaconda3\lib\site-packages\mxnet\module\module.py", line 429, in bind
    state_names=self._state_names)
  File "C:\Program Files\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "C:\Program Files\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 375, in bind_exec
    shared_group))
  File "C:\Program Files\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "C:\Program Files\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1529, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (128, 1, 32, 280)
[17:12:04] c:\jenkins\workspace\mxnet-tag\mxnet\src\executor\../common/exec_utils.h:392: InferShape pass cannot decide shapes for the following arguments (0s means unknown dimensions). Please consider providing them as inputs:
l0_init_h: [], l2_init_h: [], l1_init_h: [], l3_init_h: [], 

Process finished with exit code 1
运行到这个函数的mod.bind(for_training=False, data_shapes=data_shapes)这里出现上述错误
def load_module(prefix, epoch, data_names, data_shapes, network=None):
    """
    Loads the model from checkpoint specified by prefix and epoch, binds it
    to an executor, and sets its parameters and returns a mx.mod.Module
    """
    sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
    if network is not None:
        sym = network

    # We don't need CTC loss for prediction, just a simple softmax will suffice.
    # We get the output of the layer just before the loss layer ('pred_fc') and add softmax on top
    pred_fc = sym.get_internals()['pred_fc_output']
    sym = mx.sym.softmax(data=pred_fc)

    mod = mx.mod.Module(symbol=sym, context=mx.cpu(), data_names=data_names, label_names=None)
    mod.bind(for_training=False, data_shapes=data_shapes)
    mod.set_params(arg_params, aux_params, allow_missing=False)
    return mod

**Comment by Jinnrry** [comment]
你项目在中文路径里面？你放到英文路径试试呢，我看源码，cn_ocr.py 107行应该是初始化模型，应该是中文路径，导致加载失败了吧

**Comment by zhang0557kui** [comment]
我试了将中文路径改成英文，依然是这个问题呢：
RuntimeError: simple_bind error. Arguments:
data: (128, 1, 32, 280)
[17:33:51] c:\jenkins\workspace\mxnet-tag\mxnet\src\executor\../common/exec_utils.h:392: InferShape pass cannot decide shapes for the following arguments (0s means unknown dimensions). Please consider providing them as inputs:
l0_init_h: [], l2_init_h: [], l1_init_h: [], l3_init_h: [],

**Comment by zhang0557kui** [comment]
> 你项目在中文路径里面？你放到英文路径试试呢，我看源码，cn_ocr.py 107行应该是初始化模型，应该是中文路径，导致加载失败了吧

我试了将中文路径改成英文，依然是这个问题呢：
RuntimeError: simple_bind error. Arguments:
data: (128, 1, 32, 280)
[17:33:51] c:\jenkins\workspace\mxnet-tag\mxnet\src\executor../common/exec_utils.h:392: InferShape pass cannot decide shapes for the following arguments (0s means unknown dimensions). Please consider providing them as inputs:
l0_init_h: [], l2_init_h: [], l1_init_h: [], l3_init_h: [],

**Comment by Jinnrry** [comment]
cv_ocr.py 128行，    
`def _get_module(self, hp):
        network = crnn_lstm(hp)
        prefix = os.path.join(self._model_dir, self.MODEL_FILE_PREFIX)
        # import pdb; pdb.set_trace()
        data_names = ['data']
        data_shapes = [(data_names[0], (hp.batch_size, 1, hp.img_height, hp.img_width))]
        print(prefix,data_shapes)
        mod = load_module(prefix, self._model_epoch, data_names, data_shapes, network=network)
        return mod`

这个函数，你把prefix打印出来看看呢

**Comment by zhang0557kui** [comment]
> print(prefix,data_shapes)

C:\Users\zhangkui\AppData\Roaming\cnocr\models\model-v1.0.0 [('data', (128, 1, 32, 280))]

**Comment by Jinnrry** [comment]
你到这个文件夹里面去看看模型下载下来了吗，国内你没科学上网的话没法自动下载的。或者你是不是以前用过v0.2版本？老版本的模型不兼容新版本，得删了重新下载

**Comment by zhang0557kui** [comment]
> 你到这个文件夹里面去看看模型下载下来了吗，国内你没科学上网的话没法自动下载的。或者你是不是以前用过v0.2版本？老版本的模型不兼容新版本，得删了重新下载

![image](https://user-images.githubusercontent.com/28557916/62455666-79a93880-b7a9-11e9-8c70-d6248c5aeb18.png)

**Comment by zhang0557kui** [comment]
> 你到这个文件夹里面去看看模型下载下来了吗，国内你没科学上网的话没法自动下载的。或者你是不是以前用过v0.2版本？老版本的模型不兼容新版本，得删了重新下载

今天从百度网盘手动下的，网上下不下来

**Comment by zhang0557kui** [comment]
> 你到这个文件夹里面去看看模型下载下来了吗，国内你没科学上网的话没法自动下载的。或者你是不是以前用过v0.2版本？老版本的模型不兼容新版本，得删了重新下载

**Comment by zhang0557kui** [comment]
> cv_ocr.py 128行，
> 
> ```
> def _get_module(self, hp):
>         network = crnn_lstm(hp)
>         prefix = os.path.join(self._model_dir, self.MODEL_FILE_PREFIX)
>         # import pdb; pdb.set_trace()
>         data_names = ['data']
>         data_shapes = [(data_names[0], (hp.batch_size, 1, hp.img_height, hp.img_width))]
>         print(prefix,data_shapes)
>         mod = load_module(prefix, self._model_epoch, data_names, data_shapes, network=network)
>         return mod
> ```
> 
> 这个函数，你把prefix、data_shapes打印出来看看呢

![image](https://user-images.githubusercontent.com/28557916/62455821-c68d0f00-b7a9-11e9-9143-ec9ba82ec121.png)

**Comment by zhang0557kui** [comment]
> 你到这个文件夹里面去看看模型下载下来了吗，国内你没科学上网的话没法自动下载的。或者你是不是以前用过v0.2版本？老版本的模型不兼容新版本，得删了重新下载

今天从百度网盘手动下的，网上下不下来，下下来的压缩包命名是cnocr-models-v0.1.0

**Comment by Jinnrry** [comment]
emmm，那我也搞不定了，我只是用过这个项目，没有仔细读过源码，等作者解答吧 @breezedeus

**Comment by zhang0557kui** [comment]
> emmm，那我也搞不定了，我只是用过这个项目，没有仔细读过源码，等作者解答吧 @breezedeus

v0.1.0是不是老版本的

**Comment by Jinnrry** [comment]
是

**Comment by zhang0557kui** [comment]
>
好的，谢谢您，我找到了v1.0.0，我再试试

**Comment by zhang0557kui** [comment]
> 是

解决了，下载最新版本的model，谢谢啦

**Comment by huangmingwen** [comment]
> > 是
> 
> 解决了，下载最新版本的model，谢谢啦

你好，请问v1.0.0.0版本在哪下载？
