### ISSUE TITLE
如何减小cnocr的体积？

### ISSUE THREAD

**Issue by cqsir** [breezedeus/CnOCR#236]
想打包发布到客户端用，压缩后要200MB，有点大。

可以去掉的部分
1.训练模块
2.文字检测（应用场景简单，可以自已编程快速分离出单行做ocr）

核心代码：
```
ocr = CnOcr()#或者(det_model_name='naive_det')
out = ocr.ocr_for_single_line(img_fp)
```

**Comment by cqsir** [comment]
用spacesniffer看，torch占用一半的空间，这个模块去掉就运行不了
cnstd用到它，所以，如果不用检测，是否可以把torch去掉
```
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    from cnocr import CnOcr
  File "C:\Users\cqsir\.virtualenvs\w4-Dy8309lR\lib\site-packages\cnocr\__init__.py", line 20, in <module>
    from cnstd.consts import AVAILABLE_MODELS as DET_AVAILABLE_MODELS
  File "C:\Users\cqsir\.virtualenvs\w4-Dy8309lR\lib\site-packages\cnstd\__init__.py", line 20, in <module>
    from .detector import Detector
  File "C:\Users\cqsir\.virtualenvs\w4-Dy8309lR\lib\site-packages\cnstd\detector.py", line 31, in <module>
    from .consts import MODEL_VERSION, AVAILABLE_MODELS
  File "C:\Users\cqsir\.virtualenvs\w4-Dy8309lR\lib\site-packages\cnstd\consts.py", line 26, in <module>
    from torchvision.models import (
  File "C:\Users\cqsir\.virtualenvs\w4-Dy8309lR\lib\site-packages\torchvision\__init__.py", line 4, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```


![image](https://user-images.githubusercontent.com/17335752/224531782-237a615b-dd9c-4739-a279-094d49692bab.png)

**Comment by breezedeus** [comment]
cnocr的预测同样也会用pytorch。但如果你用onnx模型，是可以不用pytorch的，但只能自己去捋代码去掉对pytorch的依赖了，还挺麻烦的。
另一种方法是可以使用别人写的C++版：https://github.com/CoireLen/CnocrCpp ，或者 Rust 版：https://github.com/CoireLen/RustCnOCR 。

**Comment by cqsir** [comment]
改到ctc.py改不下去：），算了，大就大点。

识别率和速度都是杠杠的！
