### ISSUE TITLE
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' 

### ISSUE THREAD

**Issue by YCYAX** [breezedeus/CnOCR#242]
Traceback (most recent call last):
  File "C:\Users\18154\Desktop\slg\test.py", line 2, in <module>
    from cnocr import CnOcr
  File "C:\Users\18154\Desktop\slg\venv\Lib\site-packages\cnocr\__init__.py", line 21, in <module>
    from .cn_ocr import CnOcr, gen_model
  File "C:\Users\18154\Desktop\slg\venv\Lib\site-packages\cnocr\cn_ocr.py", line 31, in <module>
    from cnocr.models.ocr_model import OcrModel
  File "C:\Users\18154\Desktop\slg\venv\Lib\site-packages\cnocr\models\ocr_model.py", line 34, in <module>
    from .mobilenet import gen_mobilenet_v3
  File "C:\Users\18154\Desktop\slg\venv\Lib\site-packages\cnocr\models\mobilenet.py", line 25, in <module>
    from torchvision.models.mobilenetv2 import ConvBNActivation
ImportError: cannot import name 'ConvBNActivation' from 'torchvision.models.mobilenetv2' (C:\Users\18154\Desktop\slg\venv\Lib\site-packages\torchvision\models\mobilenetv2.py)

python：3.11.2
torchvision：0.15.1

**Comment by breezedeus** [comment]
更新到最新版cnocr

**Comment by YCYAX** [comment]
Could not find a version that satisfies the requirement onnxruntime (from cnocr) (from versions: none)
应该是onnxruntime在python3.11版本上没有支持

**Comment by breezedeus** [comment]
Python3.11 的确有兼容问题，建议用3.10
