### ISSUE TITLE
使用pyinstaller打包之后出错了

### ISSUE THREAD

**Issue by qq6264214** [breezedeus/CnOCR#248]
Traceback (most recent call last):
  File "main_window.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "my_thread.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "recognize.py", line 146, in <module>
  File "cnocr\cn_ocr.py", line 155, in __init__
  File "cnocr\recognizer.py", line 132, in __init__
  File "cnocr\utils.py", line 252, in read_charset
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xx\\AppData\\Local\\Temp\\_MEI41442\\cnocr\\label_cn.txt'

这个应该怎么解决呢

**Comment by 835330987** [comment]
请问大佬是怎么解决的

**Comment by pcdd-group** [comment]
使用 **--add-data** 参数

`
pyinstaller main.py --onefile --add-data "your path/python/Lib/site-packages/cnocr/label_cn.txt:cnocr"
`
