### ISSUE TITLE
导出训练好的模型报错

### ISSUE THREAD

**Issue by xiaozo** [breezedeus/CnOCR#254]
我用的cnocr版本是2.2.2.3，执行cnocr export-onnx -o /Users/ZLX_1/Desktop/cocos2d/test.onnx 命令报错:
   
  Traceback (most recent call last):
  File "/Users/ZLX_1/Library/Python/3.9/bin/cnocr", line 8, in <module>
    sys.exit(cli())
  File "/Users/ZLX_1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ZLX_1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/ZLX_1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ZLX_1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ZLX_1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ZLX_1/Library/Python/3.9/lib/python/site-packages/cnocr/cli.py", line 541, in export_onnx_model
    export_to_onnx(rec_model_name, output_model_fp, input_model_fp)
  File "/Users/ZLX_1/Library/Python/3.9/lib/python/site-packages/cnocr/cli.py", line 486, in export_to_onnx
    model = ocr._model
AttributeError: 'CnOcr' object has no attribute '_model'

**Comment by breezedeus** [comment]
你试试先用 `cnocr resave` 转存 ，再调这个命令。

**Comment by xiaozo** [comment]
好的，我试试

**Comment by cpp597455873** [comment]
cnocr resave 调用后依然报错

**Comment by HaviZou** [comment]
遇见了相同的问题，请问你导出成功了吗？
