### ISSUE TITLE
训练时，train 命令出现异常

### ISSUE THREAD

**Issue by HaviZou** [breezedeus/CnOCR#270]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\CnOCR\env\Scripts\cnocr.exe\__main__.py", line 7, in <module>
  File "D:\CnOCR\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\CnOCR\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\CnOCR\env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\CnOCR\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\CnOCR\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\CnOCR\env\lib\site-packages\cnocr\cli.py", line 165, in train
    trainer.fit(
  File "D:\CnOCR\env\lib\site-packages\cnocr\trainer.py", line 324, in fit
    self.pl_trainer.fit(pl_module, train_dataloader, val_dataloaders, datamodule)
  File "D:\CnOCR\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "D:\CnOCR\env\lib\site-packages\pytorch_lightning\trainer\call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\CnOCR\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\CnOCR\env\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 923, in _run
    _verify_loop_configurations(self)
  File "D:\CnOCR\env\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py", line 36, in _verify_loop_configurations
    __verify_train_val_loop_configuration(trainer, model)
  File "D:\CnOCR\env\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py", line 77, in __verify_train_val_loop_configuration
    raise NotImplementedError(
NotImplementedError: Support for `training_epoch_end` has been removed in v2.0.0. `WrapperLightningModule` implements this method. You can use the `on_train_epoch_end` hook instead. To access outputs, save them in-memory as instance attributes. You can find migration examples in https://github.com/Lightning-AI/lightning/pull/16520.

**Comment by HaviZou** [comment]
pytorch_lightning 版本的兼容性问题，可以试试 1.6.3 版本
