### ISSUE TITLE
图片中有无法识别的文字报错

### ISSUE THREAD

**Issue by jiangwei1995910** [breezedeus/cnocr#3]
python版本：3.7.2
操作系统：windows10
图片中有一个乱码，是这个原因吗？

Traceback (most recent call last):
  File "E:/PycharmProjects/mhxy/main.py", line 9, in <module>
    ocr = CnOcr()
  File "C:\Users\63110\AppData\Local\Programs\Python\Python37\lib\site-packages\cnocr\cn_ocr.py", line 83, in __init__
    self._alphabet, _ = read_charset(os.path.join(self._model_dir, 'label_cn.txt'))
  File "C:\Users\63110\AppData\Local\Programs\Python\Python37\lib\site-packages\cnocr\utils.py", line 65, in read_charset
    for line in fp:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 10: illegal multibyte sequence

**Comment by breezedeus** [comment]
这个mac/linux下应该没问题。。

你在cnocr\utils.py这个文件的开头加下面这行试试：
```python
# coding: utf-8
```

**Comment by jiangwei1995910** [comment]
cnocr\utils.py这个文件的第63行，输出fp，发现不是utf-8编码，我加了一个编码上去

**Comment by breezedeus** [comment]
现在没问题了？是在文件首行加的吗？

**Comment by jiangwei1995910** [comment]
不是，open文件那行代码那里，我提了个pull request过去，你可以看看

**Comment by breezedeus** [comment]
哦，看到你的pr了。多谢
