### ISSUE TITLE
mxnet.base.MXNetError

### ISSUE THREAD

**Issue by NexFord** [breezedeus/cnocr#39]
**My codes are below:**
`# *_* coding = utf-8 *_*

from cnocr import CnOcr 
png = 'E:\\python\\py\\Vitaminpic\\2018-10-29 维生素价格.png'
ocr = CnOcr() 
res = ocr.ocr(png) 
print("Predicted Chars:", res)`

**However ,I get below with latest version  mxnet--1.4.1 :**

Traceback (most recent call last):
  File "e:\python\exam\exam3.py", line 6, in <module>
    res = ocr.ocr(png)
  File "C:\Users\NexFord\AppData\Local\Programs\Python\Python37\lib\site-packages\cnocr\cn_ocr.py", line 145, in ocr
    img = mx.image.imread(img_fp, 1).asnumpy()
  File "C:\Users\NexFord\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\image\image.py", line 85, in imread
    return _internal._cvimread(filename, *args, **kwargs)
  File "<string>", line 35, in _cvimread
  File "C:\Users\NexFord\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "C:\Users\NexFord\AppData\Local\Programs\Python\Python37\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:54:53] C:\Jenkins\workspace\mxnet-tag\mxnet\src\io\image_io.cc:222: Check failed: file.is_open() Imread: 'E:\python\py\Vitaminpic\2018-10-29 维生素价格.png' couldn't open file: Invalid argument
**So ,Who is Jenkins?**

**Comment by breezedeus** [comment]
试试把文件名改成只有英文字母试试，去掉空格

**Comment by breezedeus** [comment]
试试把里面的`\`改成'/'。（windows下的python解析路径需要转义。具体可以搜下）

`png = 'E:/python/py/Vitaminpic/维生素价格.png'`

@NexFord
