### ISSUE TITLE
继续训练

### ISSUE THREAD

**Issue by yerui2018** [breezedeus/cnocr#43]
大佬，如果自己准备好训练数据（不含360W的训练数据），在已有的模型上继续训练，会不会对模型的整体识别效果产生较大的影响呢？比如，原模型能够正确识别的字，继续训练后，会导致识别错误，会有这种情况发生么？

**Comment by yerui2018** [comment]
我准备了10万的数据继续训练，使用GPU训练，有如下报错，大佬知道是什么原因吗？
`proc 0 started
proc 1 started
proc 3 started
proc 2 started
proc 0 started
2019-11-22 10:47:07,255 Loaded model /home/yerui/.cnocr/models/model-v1.0.0-0020.params
proc 1 started
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mxnet/symbol/symbol.py", line 1523, in simple_bind
    ctypes.byref(exe_handle)))
  File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:47:07] src/storage/storage.cc:116: Compile with USE_CUDA=1 to enable GPU usage

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x23d55a) [0x7f8f8677c55a]
[bt] (1) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x23dbc1) [0x7f8f8677cbc1]
[bt] (2) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x32aa805) [0x7f8f897e9805]
[bt] (3) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x32af1df) [0x7f8f897ee1df]
[bt] (4) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x32b0682) [0x7f8f897ef682]
[bt] (5) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::common::InitZeros(mxnet::NDArrayStorageType, nnvm::TShape const&, mxnet::Context const&, int)+0xa9b) [0x7f8f890ea5cb]
[bt] (6) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::common::ReshapeOrCreate(std::string const&, nnvm::TShape const&, int, mxnet::NDArrayStorageType, mxnet::Context const&, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, bool)+0x96f) [0x7f8f890f790f]
[bt] (7) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::InitArguments(nnvm::IndexedGraph const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, mxnet::Executor const*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*)+0xab0) [0x7f8f890fed50]
[bt] (8) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::string, nnvm::TShape, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, nnvm::TShape> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0x76d) [0x7f8f8910d28d]
[bt] (9) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::Executor::SimpleBind(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::vector<mxnet::Context, std::allocator<mxnet::Context> > const&, std::unordered_map<std::string, nnvm::TShape, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, nnvm::TShape> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >*, std::unordered_map<std::string, mxnet::NDArray, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, mxnet::NDArray> > >*, mxnet::Executor*)+0x1d1) [0x7f8f8910f3f1]



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/cnocr_train.py", line 179, in <module>
    run_cn_ocr(args)
  File "scripts/cnocr_train.py", line 168, in run_cn_ocr
    fit(network=network, data_train=data_train, data_val=data_val, metrics=metrics, args=args, hp=hp, data_names=data_names)
  File "/home/yerui/OCR/mxocr/cnocr/cnocr/fit/fit.py", line 73, in fit
    epoch_end_callback=mx.callback.do_checkpoint(args.prefix),
  File "/usr/local/lib/python3.6/dist-packages/mxnet/module/base_module.py", line 499, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python3.6/dist-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python3.6/dist-packages/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python3.6/dist-packages/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/usr/local/lib/python3.6/dist-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python3.6/dist-packages/mxnet/symbol/symbol.py", line 1529, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (128, 1, 32, 280)
label: (128, 10)
[10:47:07] src/storage/storage.cc:116: Compile with USE_CUDA=1 to enable GPU usage
`

**Comment by yerui2018** [comment]
> 我准备了10万的数据继续训练，使用GPU训练，有如下报错，大佬知道是什么原因吗？
> `proc 0 started
> proc 1 started
> proc 3 started
> proc 2 started
> proc 0 started
> 2019-11-22 10:47:07,255 Loaded model /home/yerui/.cnocr/models/model-v1.0.0-0020.params
> proc 1 started
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/dist-packages/mxnet/symbol/symbol.py", line 1523, in simple_bind
> ctypes.byref(exe_handle)))
> File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 252, in check_call
> raise MXNetError(py_str(_LIB.MXGetLastError()))
> mxnet.base.MXNetError: [10:47:07] src/storage/storage.cc:116: Compile with USE_CUDA=1 to enable GPU usage
> 
> Stack trace returned 10 entries:
> [bt] (0) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x23d55a) [0x7f8f8677c55a]
> [bt] (1) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x23dbc1) [0x7f8f8677cbc1]
> [bt] (2) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x32aa805) [0x7f8f897e9805]
> [bt] (3) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x32af1df) [0x7f8f897ee1df]
> [bt] (4) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(+0x32b0682) [0x7f8f897ef682]
> [bt] (5) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::common::InitZeros(mxnet::NDArrayStorageType, nnvm::TShape const&, mxnet::Context const&, int)+0xa9b) [0x7f8f890ea5cb]
> [bt] (6) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::common::ReshapeOrCreate(std::string const&, nnvm::TShape const&, int, mxnet::NDArrayStorageType, mxnet::Context const&, std::unordered_map<std::string, mxnet::NDArray, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, mxnet::NDArray> > >_, bool)+0x96f) [0x7f8f890f790f] [bt] (7) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::InitArguments(nnvm::IndexedGraph const&, std::vector<nnvm::TShape, std::allocatornnvm::TShape > const&, std::vector<int, std::allocator > const&, std::vector<int, std::allocator > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType > const&, std::unordered_set<std::string, std::hashstd::string, std::equal_tostd::string, std::allocatorstd::string > const&, mxnet::Executor const_, std::unordered_map<std::string, mxnet::NDArray, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, mxnet::NDArray> > >_, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_)+0xab0) [0x7f8f890fed50]
> [bt] (8) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::lessstd::string, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::unordered_map<std::string, nnvm::TShape, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, nnvm::TShape> > > const&, std::unordered_map<std::string, int, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType > const&, std::unordered_set<std::string, std::hashstd::string, std::equal_tostd::string, std::allocatorstd::string > const&, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::unordered_map<std::string, mxnet::NDArray, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, mxnet::NDArray> > >_, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0x76d) [0x7f8f8910d28d]
> [bt] (9) /usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so(mxnet::Executor::SimpleBind(nnvm::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::lessstd::string, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::vector<mxnet::Context, std::allocatormxnet::Context > const&, std::unordered_map<std::string, nnvm::TShape, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, nnvm::TShape> > > const&, std::unordered_map<std::string, int, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, int> > > const&, std::unordered_map<std::string, int, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, int> > > const&, std::vector<mxnet::OpReqType, std::allocatormxnet::OpReqType > const&, std::unordered_set<std::string, std::hashstd::string, std::equal_tostd::string, std::allocatorstd::string > const&, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::vector<mxnet::NDArray, std::allocatormxnet::NDArray >_, std::unordered_map<std::string, mxnet::NDArray, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<std::string const, mxnet::NDArray> > >_, mxnet::Executor*)+0x1d1) [0x7f8f8910f3f1]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "scripts/cnocr_train.py", line 179, in
> run_cn_ocr(args)
> File "scripts/cnocr_train.py", line 168, in run_cn_ocr
> fit(network=network, data_train=data_train, data_val=data_val, metrics=metrics, args=args, hp=hp, data_names=data_names)
> File "/home/yerui/OCR/mxocr/cnocr/cnocr/fit/fit.py", line 73, in fit
> epoch_end_callback=mx.callback.do_checkpoint(args.prefix),
> File "/usr/local/lib/python3.6/dist-packages/mxnet/module/base_module.py", line 499, in fit
> for_training=True, force_rebind=force_rebind)
> File "/usr/local/lib/python3.6/dist-packages/mxnet/module/module.py", line 429, in bind
> state_names=self._state_names)
> File "/usr/local/lib/python3.6/dist-packages/mxnet/module/executor_group.py", line 279, in **init**
> self.bind_exec(data_shapes, label_shapes, shared_group)
> File "/usr/local/lib/python3.6/dist-packages/mxnet/module/executor_group.py", line 375, in bind_exec
> shared_group))
> File "/usr/local/lib/python3.6/dist-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
> shared_buffer=shared_data_arrays, **input_shapes)
> File "/usr/local/lib/python3.6/dist-packages/mxnet/symbol/symbol.py", line 1529, in simple_bind
> raise RuntimeError(error_msg)
> RuntimeError: simple_bind error. Arguments:
> data: (128, 1, 32, 280)
> label: (128, 10)
> [10:47:07] src/storage/storage.cc:116: Compile with USE_CUDA=1 to enable GPU usage
> `

不好意思 安装的cpu版本。重新安装了GPU版本解决了。

**Comment by yerui2018** [comment]
好的。我自己试试看。
