### ISSUE TITLE
输入ocr = CnOcr()报错

### ISSUE THREAD

**Issue by yuanqin27** [breezedeus/cnocr#49]
按照教程，先安装后导入包，结果报如下错误：
 1 attempt left
Downloading /home/yqli/.cnocr/cnocr-models-v1.0.0.zip from https://www.dropbox.com/s/7w8l3mk4pvkt34w/cnocr-models-v1.0.0.zip?dl=1...
Traceback (most recent call last):
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7faa2f72c9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/7w8l3mk4pvkt34w/cnocr-models-v1.0.0.zip?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faa2f72c9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/cnocr/cn_ocr.py", line 101, in __init__
    self._assert_and_prepare_model_files(root)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/cnocr/cn_ocr.py", line 126, in _assert_and_prepare_model_files
    get_model_file(root)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/cnocr/utils.py", line 69, in get_model_file
    download(MODEL_BASE_URL, path=zip_file_path, overwrite=True)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/mxnet/gluon/utils.py", line 342, in download
    raise e
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/mxnet/gluon/utils.py", line 309, in download
    r = requests.get(url, stream=True, verify=verify_ssl)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/yqli/anaconda3/envs/practice/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/7w8l3mk4pvkt34w/cnocr-models-v1.0.0.zip?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faa2f72c9b0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
在Windows下这一步也是报错

**Comment by breezedeus** [comment]
从Dropbox下载需要翻墙，如果不行就从百度云链接先下好

**Comment by yuanqin27** [comment]
翻之前的问题，已找到答案解决，感谢回复~
