### ISSUE TITLE
从网盘下载了model,放到cnocr文件夹下，但是运行程序一直要去下载

### ISSUE THREAD

**Issue by billyyong** [breezedeus/cnocr#59]
从网盘下载了model,放到cnocr文件夹下，但是运行程序一直要去下载，后来我自己解压了，把models 文件夹放在cnocr文件夹下，这样也不行，后来发现时models下面文件的文件名不同，改了文件名，跳过了下载，后面又出错了，
[21:51:57] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v1.3.1. Attempting to upgrade...
[21:51:57] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1523, in simple_bind
    ctypes.byref(exe_handle)))
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:51:57] c:\jenkins\workspace\mxnet-tag\mxnet\src\executor\../common/exec_utils.h:392: InferShape pass cannot decide shapes for the following arguments (0s means unknown dimensions). Please consider providing them as inputs:
l0_init_h: [], l2_init_h: [], l1_init_h: [], l3_init_h: [], 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/OCR/ocrtest.py", line 2, in <module>
    ocr = CnOcr()
  File "C:\ProgramData\Anaconda3\lib\site-packages\cnocr\cn_ocr.py", line 107, in __init__
    self._mod = self._get_module(self._hp)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cnocr\cn_ocr.py", line 134, in _get_module
    mod = load_module(prefix, self._model_epoch, data_names, data_shapes, network=network)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cnocr\cn_ocr.py", line 90, in load_module
    mod.bind(for_training=False, data_shapes=data_shapes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\module\module.py", line 429, in bind
    state_names=self._state_names)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 375, in bind_exec
    shared_group))
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\module\executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\symbol\symbol.py", line 1529, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (128, 1, 32, 280)
[21:51:57] c:\jenkins\workspace\mxnet-tag\mxnet\src\executor\../common/exec_utils.h:392: InferShape pass cannot decide shapes for the following arguments (0s means unknown dimensions). Please consider providing them as inputs:
l0_init_h: [], l2_init_h: [], l1_init_h: [], l3_init_h: [],

**Comment by breezedeus** [comment]
名字不对？那是不是你下的版本不对。新版模型名字和包都是v1.0
