### ISSUE TITLE
windows下中文文件名提示 No such file or directory

### ISSUE THREAD

**Issue by duanyukai** [breezedeus/cnocr#62]
```
Traceback (most recent call last):
  File "H:\main.py", line 16, in <module>
    res = ocr.ocr('H:\\输入\\1.jpg')
  File "H:\venv\lib\site-packages\cnocr\cn_ocr.py", line 145, in ocr
    img = mx.image.imread(img_fp, 1).asnumpy()
  File "H:\venv\lib\site-packages\mxnet\image\image.py", line 85, in imread
    return _internal._cvimread(filename, *args, **kwargs)
  File "<string>", line 35, in _cvimread
  File "H:\venv\lib\site-packages\mxnet\_ctypes\ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "H:\venv\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:13:49] C:\Jenkins\workspace\mxnet-tag\mxnet\src\io\image_io.cc:222: Check failed: file.is_open() Imread: 'H:\输入\1.jpg' couldn't open file: No such file or directory

Process finished with exit code 1

```

windows系统下部分用户的电脑用户名为中文，不获取权限的情况下，只能拿到路径中含有中文的temp文件夹，不过套了一层读取文件先解决也问题不大。

**Comment by breezedeus** [comment]
@duanyukai 路径名写成这样试试：“H:/输入/1.jpg” ，参考 https://blog.csdn.net/jusulysunbeamy/article/details/51290080
